name: C++ Linting

on: [pull_request]

jobs:
  clang-tidy-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: clang-tidy review
        uses: ZedThree/clang-tidy-review@v0.23.0
        with:
          build_dir: .
          config_file: ''
        continue-on-error: true
        
      - name: Upload review comments
        uses: ZedThree/clang-tidy-review/upload@v0.23.0
        continue-on-error: true